name: Flutter Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.7.1
        with:
          channel: 'stable'
          
      - name: Restore packages
        run: flutter pub get
        
      - name: Analyze
        run:   flutter analyze

      - name: Run tests
        run: flutter test --coverage
        
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
