name: Flutter Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'
          
      - name: Restore packages
        working-directory: fmfu
        run: flutter pub get
        
      - name: Analyze
        working-directory: fmfu
        run:   flutter analyze

      - name: Run tests
        working-directory: fmfu
        run: flutter test --coverage
        
      - name: Upload coverage to codecov
        working-directory: fmfu
        run: curl -s https://codecov.io/bash
        shell: bash
